# fly.toml app configuration file generated for imove-api-server on 2024-04-05T16:11:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'imove-api-server'
primary_region = 'syd'

[build]

[[mounts]]
  source = 'imove_data'
  destination = '/data'
  initial_size = '1gb'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '16gb'
  cpu_kind = 'shared'
  cpus = 8
